name:               "Merafour"
description:        "一个人一辆单车走天涯"

url:                ""
author:             "Merafour"
email:              "Merafour@163.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "Merafour"
email:              "Merafour@163.com"
github:             "Merafour"
pinterest:          "jhondoe"
linkedin:           "jhondoe"
facebook:           "jhondoe"

disqus_shortname:   "thinker3197"

background:         "https://github.com/Merafour/MerafourImage/blob/master/merafour.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate